-- Generated by reforge build. Edit reforge.json instead.
return {
	schema = 1,
	redirects = {
		{ stock = "bundle/data/51/51f7e0e66641669b", file = "payload/redirect/51f7e0e66641669b.btmat", sha256 = "078ed294f4bab50fa984a035d9c94da4e5521da858c148cc52316f5fcfe448e8" },
		{ stock = "bundle/data/59/59c4260bff372016", file = "payload/redirect/59c4260bff372016.btmat", sha256 = "c49cba30643a8c863c2818df51bbf5f761f7dc0cd32c4912b3d51d037e655db4" },
		{ stock = "bundle/data/97/97b5490a85966a77", file = "payload/redirect/97b5490a85966a77.btmat", sha256 = "28a94fa9b2a988d8dd93925c40e4687091b6e766f57d1c283eab9fddbaa03a03" },
		{ stock = "bundle/data/ba/bacd9b3be2a4c57f", file = "payload/redirect/bacd9b3be2a4c57f.btmat", sha256 = "e0d63444385473b9b4e299318cd3fdc85e2188f9df9da06ab2224a41654cb616" },
	},
}
